// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: protos/user_servise/user_servise.proto

package user_servise

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Slise struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nums []int32 `protobuf:"varint,1,rep,packed,name=nums,proto3" json:"nums,omitempty"`
}

func (x *Slise) Reset() {
	*x = Slise{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slise) ProtoMessage() {}

func (x *Slise) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slise.ProtoReflect.Descriptor instead.
func (*Slise) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{0}
}

func (x *Slise) GetNums() []int32 {
	if x != nil {
		return x.Nums
	}
	return nil
}

type MaxNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Maxnum int32 `protobuf:"varint,1,opt,name=maxnum,proto3" json:"maxnum,omitempty"`
}

func (x *MaxNum) Reset() {
	*x = MaxNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxNum) ProtoMessage() {}

func (x *MaxNum) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxNum.ProtoReflect.Descriptor instead.
func (*MaxNum) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{1}
}

func (x *MaxNum) GetMaxnum() int32 {
	if x != nil {
		return x.Maxnum
	}
	return 0
}

type Nums struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int32 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Nums) Reset() {
	*x = Nums{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nums) ProtoMessage() {}

func (x *Nums) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nums.ProtoReflect.Descriptor instead.
func (*Nums) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{2}
}

func (x *Nums) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Nums) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type Sum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int32 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *Sum) Reset() {
	*x = Sum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sum) ProtoMessage() {}

func (x *Sum) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sum.ProtoReflect.Descriptor instead.
func (*Sum) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{3}
}

func (x *Sum) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

type UserPrimayKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserPrimayKey) Reset() {
	*x = UserPrimayKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPrimayKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPrimayKey) ProtoMessage() {}

func (x *UserPrimayKey) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPrimayKey.ProtoReflect.Descriptor instead.
func (*UserPrimayKey) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{4}
}

func (x *UserPrimayKey) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Age      int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type DivReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num1 float32 `protobuf:"fixed32,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2 float32 `protobuf:"fixed32,2,opt,name=num2,proto3" json:"num2,omitempty"`
}

func (x *DivReq) Reset() {
	*x = DivReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivReq) ProtoMessage() {}

func (x *DivReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivReq.ProtoReflect.Descriptor instead.
func (*DivReq) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{6}
}

func (x *DivReq) GetNum1() float32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *DivReq) GetNum2() float32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type DivResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num3 float32 `protobuf:"fixed32,1,opt,name=num3,proto3" json:"num3,omitempty"`
}

func (x *DivResp) Reset() {
	*x = DivResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivResp) ProtoMessage() {}

func (x *DivResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivResp.ProtoReflect.Descriptor instead.
func (*DivResp) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{7}
}

func (x *DivResp) GetNum3() float32 {
	if x != nil {
		return x.Num3
	}
	return 0
}

type MultReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num1 float32 `protobuf:"fixed32,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2 float32 `protobuf:"fixed32,2,opt,name=num2,proto3" json:"num2,omitempty"`
}

func (x *MultReq) Reset() {
	*x = MultReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultReq) ProtoMessage() {}

func (x *MultReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultReq.ProtoReflect.Descriptor instead.
func (*MultReq) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{8}
}

func (x *MultReq) GetNum1() float32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *MultReq) GetNum2() float32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type MultResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num3 float32 `protobuf:"fixed32,1,opt,name=num3,proto3" json:"num3,omitempty"`
}

func (x *MultResp) Reset() {
	*x = MultResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultResp) ProtoMessage() {}

func (x *MultResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultResp.ProtoReflect.Descriptor instead.
func (*MultResp) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{9}
}

func (x *MultResp) GetNum3() float32 {
	if x != nil {
		return x.Num3
	}
	return 0
}

type SubtReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num1 float32 `protobuf:"fixed32,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2 float32 `protobuf:"fixed32,2,opt,name=num2,proto3" json:"num2,omitempty"`
}

func (x *SubtReq) Reset() {
	*x = SubtReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubtReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtReq) ProtoMessage() {}

func (x *SubtReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtReq.ProtoReflect.Descriptor instead.
func (*SubtReq) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{10}
}

func (x *SubtReq) GetNum1() float32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *SubtReq) GetNum2() float32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type SubtResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num3 float32 `protobuf:"fixed32,1,opt,name=num3,proto3" json:"num3,omitempty"`
}

func (x *SubtResp) Reset() {
	*x = SubtResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubtResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtResp) ProtoMessage() {}

func (x *SubtResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtResp.ProtoReflect.Descriptor instead.
func (*SubtResp) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{11}
}

func (x *SubtResp) GetNum3() float32 {
	if x != nil {
		return x.Num3
	}
	return 0
}

type SqrtReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num1 float32 `protobuf:"fixed32,1,opt,name=num1,proto3" json:"num1,omitempty"`
}

func (x *SqrtReq) Reset() {
	*x = SqrtReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SqrtReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqrtReq) ProtoMessage() {}

func (x *SqrtReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqrtReq.ProtoReflect.Descriptor instead.
func (*SqrtReq) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{12}
}

func (x *SqrtReq) GetNum1() float32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

type SqrtResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num3 float32 `protobuf:"fixed32,1,opt,name=num3,proto3" json:"num3,omitempty"`
}

func (x *SqrtResp) Reset() {
	*x = SqrtResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SqrtResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqrtResp) ProtoMessage() {}

func (x *SqrtResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqrtResp.ProtoReflect.Descriptor instead.
func (*SqrtResp) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{13}
}

func (x *SqrtResp) GetNum3() float32 {
	if x != nil {
		return x.Num3
	}
	return 0
}

type PowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num1 float32 `protobuf:"fixed32,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2 float32 `protobuf:"fixed32,2,opt,name=num2,proto3" json:"num2,omitempty"`
}

func (x *PowReq) Reset() {
	*x = PowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowReq) ProtoMessage() {}

func (x *PowReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowReq.ProtoReflect.Descriptor instead.
func (*PowReq) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{14}
}

func (x *PowReq) GetNum1() float32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *PowReq) GetNum2() float32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type PowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num3 float32 `protobuf:"fixed32,1,opt,name=num3,proto3" json:"num3,omitempty"`
}

func (x *PowResp) Reset() {
	*x = PowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowResp) ProtoMessage() {}

func (x *PowResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowResp.ProtoReflect.Descriptor instead.
func (*PowResp) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{15}
}

func (x *PowResp) GetNum3() float32 {
	if x != nil {
		return x.Num3
	}
	return 0
}

type MnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nums []int32 `protobuf:"varint,1,rep,packed,name=nums,proto3" json:"nums,omitempty"`
}

func (x *MnReq) Reset() {
	*x = MnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MnReq) ProtoMessage() {}

func (x *MnReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MnReq.ProtoReflect.Descriptor instead.
func (*MnReq) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{16}
}

func (x *MnReq) GetNums() []int32 {
	if x != nil {
		return x.Nums
	}
	return nil
}

type MnResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *MnResp) Reset() {
	*x = MnResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_servise_user_servise_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MnResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MnResp) ProtoMessage() {}

func (x *MnResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_servise_user_servise_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MnResp.ProtoReflect.Descriptor instead.
func (*MnResp) Descriptor() ([]byte, []int) {
	return file_protos_user_servise_user_servise_proto_rawDescGZIP(), []int{17}
}

func (x *MnResp) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_protos_user_servise_user_servise_proto protoreflect.FileDescriptor

var file_protos_user_servise_user_servise_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x73, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x05, 0x53, 0x6c, 0x69, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6e,
	0x75, 0x6d, 0x73, 0x22, 0x20, 0x0a, 0x06, 0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x78, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d,
	0x61, 0x78, 0x6e, 0x75, 0x6d, 0x22, 0x22, 0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x73, 0x12, 0x0c, 0x0a,
	0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x62, 0x22, 0x13, 0x0a, 0x03, 0x53, 0x75, 0x6d,
	0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x61, 0x22, 0x1f,
	0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x79, 0x4b, 0x65, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x45, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x30, 0x0a, 0x06, 0x44, 0x69, 0x76, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x6e, 0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x22, 0x1d, 0x0a, 0x07, 0x44, 0x69, 0x76, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x33, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x33, 0x22, 0x31, 0x0a, 0x07, 0x4d, 0x75, 0x6c, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x22, 0x1e, 0x0a, 0x08, 0x4d, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x33, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x33, 0x22, 0x31, 0x0a, 0x07, 0x53, 0x75,
	0x62, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d,
	0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x22, 0x1e, 0x0a,
	0x08, 0x53, 0x75, 0x62, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d,
	0x33, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x33, 0x22, 0x1d, 0x0a,
	0x07, 0x53, 0x71, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x22, 0x1e, 0x0a, 0x08,
	0x53, 0x71, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x33,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x33, 0x22, 0x30, 0x0a, 0x06,
	0x50, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75,
	0x6d, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x22, 0x1d,
	0x0a, 0x07, 0x50, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d,
	0x33, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x33, 0x22, 0x1b, 0x0a,
	0x05, 0x4d, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x22, 0x1a, 0x0a, 0x06, 0x4d, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x32, 0x96, 0x04, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x79, 0x4b,
	0x65, 0x79, 0x1a, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x04, 0x53, 0x75, 0x6d, 0x6d,
	0x12, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x2e,
	0x4e, 0x75, 0x6d, 0x73, 0x1a, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x6d, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x03, 0x4d, 0x61, 0x78,
	0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x2e,
	0x53, 0x6c, 0x69, 0x73, 0x65, 0x1a, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x73, 0x65, 0x2e, 0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x22, 0x00, 0x12, 0x3c, 0x0a,
	0x0b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x73, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x2e, 0x4d, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x73, 0x65, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x08,
	0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x76, 0x52, 0x65, 0x71, 0x1a, 0x15,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x2e, 0x44, 0x69,
	0x76, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0a, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52,
	0x6f, 0x6f, 0x74, 0x12, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x73, 0x65, 0x2e, 0x53, 0x71, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x2e, 0x53, 0x71, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x34, 0x0a, 0x05, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x77, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65,
	0x2e, 0x50, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x08, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x4d, 0x69, 0x6e, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x73, 0x65, 0x2e, 0x4d, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x2e, 0x4d, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x15, 0x5a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_user_servise_user_servise_proto_rawDescOnce sync.Once
	file_protos_user_servise_user_servise_proto_rawDescData = file_protos_user_servise_user_servise_proto_rawDesc
)

func file_protos_user_servise_user_servise_proto_rawDescGZIP() []byte {
	file_protos_user_servise_user_servise_proto_rawDescOnce.Do(func() {
		file_protos_user_servise_user_servise_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_user_servise_user_servise_proto_rawDescData)
	})
	return file_protos_user_servise_user_servise_proto_rawDescData
}

var file_protos_user_servise_user_servise_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_protos_user_servise_user_servise_proto_goTypes = []interface{}{
	(*Slise)(nil),         // 0: user_servise.Slise
	(*MaxNum)(nil),        // 1: user_servise.MaxNum
	(*Nums)(nil),          // 2: user_servise.Nums
	(*Sum)(nil),           // 3: user_servise.Sum
	(*UserPrimayKey)(nil), // 4: user_servise.UserPrimayKey
	(*User)(nil),          // 5: user_servise.User
	(*DivReq)(nil),        // 6: user_servise.DivReq
	(*DivResp)(nil),       // 7: user_servise.DivResp
	(*MultReq)(nil),       // 8: user_servise.MultReq
	(*MultResp)(nil),      // 9: user_servise.MultResp
	(*SubtReq)(nil),       // 10: user_servise.SubtReq
	(*SubtResp)(nil),      // 11: user_servise.SubtResp
	(*SqrtReq)(nil),       // 12: user_servise.SqrtReq
	(*SqrtResp)(nil),      // 13: user_servise.SqrtResp
	(*PowReq)(nil),        // 14: user_servise.PowReq
	(*PowResp)(nil),       // 15: user_servise.PowResp
	(*MnReq)(nil),         // 16: user_servise.MnReq
	(*MnResp)(nil),        // 17: user_servise.MnResp
}
var file_protos_user_servise_user_servise_proto_depIdxs = []int32{
	4,  // 0: user_servise.UserServise.GetUserById:input_type -> user_servise.UserPrimayKey
	2,  // 1: user_servise.UserServise.Summ:input_type -> user_servise.Nums
	0,  // 2: user_servise.UserServise.Max:input_type -> user_servise.Slise
	10, // 3: user_servise.UserServise.Subtraction:input_type -> user_servise.SubtReq
	8,  // 4: user_servise.UserServise.Multiplication:input_type -> user_servise.MultReq
	6,  // 5: user_servise.UserServise.Division:input_type -> user_servise.DivReq
	12, // 6: user_servise.UserServise.SquareRoot:input_type -> user_servise.SqrtReq
	14, // 7: user_servise.UserServise.Power:input_type -> user_servise.PowReq
	16, // 8: user_servise.UserServise.ArrayMin:input_type -> user_servise.MnReq
	5,  // 9: user_servise.UserServise.GetUserById:output_type -> user_servise.User
	3,  // 10: user_servise.UserServise.Summ:output_type -> user_servise.Sum
	1,  // 11: user_servise.UserServise.Max:output_type -> user_servise.MaxNum
	11, // 12: user_servise.UserServise.Subtraction:output_type -> user_servise.SubtResp
	9,  // 13: user_servise.UserServise.Multiplication:output_type -> user_servise.MultResp
	7,  // 14: user_servise.UserServise.Division:output_type -> user_servise.DivResp
	13, // 15: user_servise.UserServise.SquareRoot:output_type -> user_servise.SqrtResp
	15, // 16: user_servise.UserServise.Power:output_type -> user_servise.PowResp
	17, // 17: user_servise.UserServise.ArrayMin:output_type -> user_servise.MnResp
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_protos_user_servise_user_servise_proto_init() }
func file_protos_user_servise_user_servise_proto_init() {
	if File_protos_user_servise_user_servise_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_user_servise_user_servise_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slise); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nums); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPrimayKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubtReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubtResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SqrtReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SqrtResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_servise_user_servise_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MnResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_user_servise_user_servise_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_user_servise_user_servise_proto_goTypes,
		DependencyIndexes: file_protos_user_servise_user_servise_proto_depIdxs,
		MessageInfos:      file_protos_user_servise_user_servise_proto_msgTypes,
	}.Build()
	File_protos_user_servise_user_servise_proto = out.File
	file_protos_user_servise_user_servise_proto_rawDesc = nil
	file_protos_user_servise_user_servise_proto_goTypes = nil
	file_protos_user_servise_user_servise_proto_depIdxs = nil
}
